#Makefile

CXX=g++
CXXFLAGS=-std=c++1y -Wall -pedantic
PROG=-o testRAT
SOURCES=parser.cpp tables.cpp testfile.cpp
HEADERS=parser.h parser.h

all: $(SOURCES) $(HEADERS)
	$(CXX) $(CXXFLAGS) $(PROG) $(SOURCES)

debug: $(SOURCES) $(HEADERS)
	$(CXX) $(CXXFLAGS) -g -o rat_debug $(SOURCES)

clean:
	rm -f rat rat_debug
